#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
#
#notes:
#At the BEGINNING, we want:
#an empty array
#two values, a and b.
#adding a and b together gives a value to push into the array
#after the value is pushed:
#b becomes a
#value becomes b
#repeat until array is filled.
#right?
